# Generated by Django 5.2.4 on 2025-07-30 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_location_lat",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "current_location_lon",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "pickup_location_lat",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "pickup_location_lon",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "dropoff_location_lat",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "dropoff_location_lon",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("time_to_pickup", models.DurationField()),
                ("time_to_dropoff", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Stops",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OFF_DUTY", "Off Duty"),
                            ("SLEEPER_BERTH", "Sleeper Berth"),
                            ("DRIVING", "Driving"),
                            ("ON_DUTY", "On Duty (Not Driving)"),
                        ],
                        max_length=32,
                    ),
                ),
                ("remark", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="RouteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OFF_DUTY", "Off Duty"),
                            ("SLEEPER_BERTH", "Sleeper Berth"),
                            ("DRIVING", "Driving"),
                            ("ON_DUTY", "On Duty (Not Driving)"),
                        ],
                        max_length=32,
                    ),
                ),
                ("stops", models.ManyToManyField(to="core.stops")),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_start_date", models.DateTimeField()),
                (
                    "current_used_cycle",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "delivery_info",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.deliveryinfo",
                    ),
                ),
                ("route_info", models.ManyToManyField(to="core.routeinfo")),
            ],
        ),
    ]
