# Generated by Django 5.2.4 on 2025-07-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routeinfo",
            name="end_location_lat",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name="routeinfo",
            name="end_location_lon",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name="routeinfo",
            name="start_location_lat",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name="routeinfo",
            name="start_location_lon",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name="stops",
            name="location_lat",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name="stops",
            name="location_lon",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
