# Generated by Django 5.2.4 on 2025-07-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_routeinfo_end_location_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="routeinfo",
            name="remaining_cycle",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
